apiVersion: skaffold/v2beta12
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: k8_demo/app
      context: app
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: ./app.py
            dest: .
    - image: k8_demo/api
      context: api
      docker: 
        dockerfile: Dockerfile
      sync:
        manual:
          - src: ./api.py
            dest: .	    
deploy:
  kubectl: 
    manifests:
      - k8s/ingress-service.yaml
      - k8s/app-pod.yaml
      - k8s/app-service.yaml
      - k8s/api-pod.yaml
      - k8s/api-service.yaml      